image:
  flavor: bookworm
  isWindows: false
  pullPolicy: Always
  repository: ghcr.io/clemlesne/azure-pipelines-agent
  version: "" # Overrides the image tag whose default is the chart "appVersion"

fullnameOverride: ""
imagePullSecrets: []
nameOverride: ""

replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 0
  maxReplicas: 100 # Arbitrary value to avoid misconfiguration; can be enlarged if needed

pipelines:
  capabilities: []
  organizationURL: null
  personalAccessToken: null
  poolName: null
  timeout: 3600 # 1 hour, in seconds
  cleanup:
    failed: 100 # In Jobs
    successful: 100 # In Jobs
    ttl: 3600 # 1 hour, in seconds
  cache:
    size: 10Gi
    type: managed-csi
    volumeEnabled: true
  tmpdir:
    size: 1Gi
    type: managed-csi
    volumeEnabled: true

secret:
  create: true
  name: "" # If not set, name is generated

serviceAccount:
  annotations: {}
  create: true
  name: "" # If not set, name is generated

# Customize security context and policies.
#
# Like, to be used with img or BuildKit:
#
# podSecurityContext:
#   procMount: Unmasked
podSecurityContext: {}

# securityContext:
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000
securityContext: {}

resources:
  limits:
    cpu: 2
    ephemeral-storage: 8Gi
    memory: 4Gi
  requests:
    cpu: 1
    ephemeral-storage: 2Gi
    memory: 2Gi

extraNodeSelectors: {}

tolerations: []

affinity: {}

# Annotation to customize various scheduling and security behaviors.
#
# Like, to be used with img or BuildKit:
#
# annotations:
#   container.apparmor.security.beta.kubernetes.io/azp-agent: unconfined
#   container.seccomp.security.alpha.kubernetes.io/azp-agent: unconfined
annotations: {}

# Additional environment variables for the agent container.
#
# Like:
#
# - name: XXX
#   value: YYY
#
# Or, reference to a secret or configmap:
#
# - name: SPECIAL_LEVEL_KEY
#   valueFrom:
#     configMapKeyRef:
#       name: special-config
#       key: special.how
#
# - name: SECRET_KEY
#   valueFrom:
#     secretKeyRef:
#       name: secret-name
#       key: secret.key
extraEnv: []

# Additional volumes for the agent pod.
#
# extraVolumes:
#   - name: config-volume
#     configMap:
#      name: special-config
extraVolumes: []

# Additional volume mounts for the agent container.
#
# extraVolumeMounts:
#   - name: config-volume
#     mountPath: /etc/special
#     readOnly: true
extraVolumeMounts: []

# Init containers for the agent pod.
#
# initContainers:
#   - name: init-container
#     image: busybox
#     command: ["/bin/sh", "-c", "echo Hello World"]
initContainers: []
